[build]
  publish = "pmacs_system_frenddvlp"

# Redirect root to login page
[[redirects]]
  from = "/"
  to = "/login_page/index.html"
  status = 200

# Catch-all 404 back to login
[[redirects]]
  from = "/*"
  to = "/login_page/index.html"
  status = 404